name: validate

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize] # This will trigger the workflow only when a PR is opened or updated with new commits
  workflow_dispatch:

jobs:
  sushi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Validate with Sushi
        run: sushi .
      
      - name: Update publisher
        run: cp _updatePublisher.sh /tmp/_updatePublisher.sh && bash /tmp/_updatePublisher.sh -f -y

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Run publisher
        run: ./_genonce.sh
      